version: '3.8'
services:

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: dev
    command: make watch
    volumes:
      - ./:/usr/src
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: postgres:14.2-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - db_vol:/var/lib/postgresql/data
    logging:
      driver: none

volumes:
  db_vol:
